// Reads icons/*.png and writes icons.gen.ts with the bytes embedded as base64,
// so the compiled desktop binary needs no asset files on disk.
// Usage: deno run -A scripts/embed_icons.ts

// Icon names: ICON_<c><p>[ _DARK] where c=caffeinate, p=pmset, 0=off, 1=on.
const files = [
  ["tray-00.png", "ICON_00"],
  ["tray-00-dark.png", "ICON_00_DARK"],
  ["tray-01.png", "ICON_01"],
  ["tray-01-dark.png", "ICON_01_DARK"],
  ["tray-10.png", "ICON_10"],
  ["tray-10-dark.png", "ICON_10_DARK"],
  ["tray-11.png", "ICON_11"],
  ["tray-11-dark.png", "ICON_11_DARK"],
] as const;

let out = "// Generated by scripts/embed_icons.ts. Do not edit.\n";
for (const [file, name] of files) {
  const bytes = await Deno.readFile(`icons/${file}`);
  out += `export const ${name} = Uint8Array.fromBase64(\n  "${bytes.toBase64()}",\n);\n`;
}
await Deno.writeTextFile("icons.gen.ts", out);
console.log("wrote icons.gen.ts");
